version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/opt/emporium
    environment:
      ALLOWED_HOSTS: localhost
      DEBUG: 1
      SECRET_KEY: notasecret
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://redis
    ports:
      - 8000:8000
    command: pipenv run python emporium/manage.py runserver 0.0.0.0:8000
  worker:
    build:
      context: .
    volumes:
      - .:/opt/emporium
    environment:
      DEBUG: 1
      SECRET_KEY: notasecret
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://redis
    command: pipenv run python emporium/manage.py rqworker default
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5
