version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run emporium/manage.py test
