version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            make bootstrap-dev
      - run:
          command: |
            pipenv run make fix
            git diff --exit-code # Error if fix changed things, to ensure stability
      - run:
          command: pipenv run make check
      - run:
          command: pipenv run make collectstatic
      - run:
          command: pipenv run make test
