# Generated by Django 2.1.4 on 2018-12-13 17:00

from django.db import migrations, models

import emporium.validators


class Migration(migrations.Migration):
    dependencies = [("emporium", "0002_auto_20181207_1658")]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                max_length=120,
                unique=True,
                validators=[emporium.validators.validate_package_name_exists],
            ),
        )
    ]
