# Generated by Django 2.1.4 on 2018-12-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("emporium", "0003_auto_20181213_1700")]

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification", models.CharField(max_length=1000)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emporium.Package",
                    ),
                ),
                (
                    "package_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emporium.PackageVersion",
                    ),
                ),
            ],
        )
    ]
