# Generated by Django 2.1.4 on 2018-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("emporium", "0004_dependency")]

    operations = [
        migrations.AlterModelOptions(
            name="dependency", options={"verbose_name_plural": "Dependencies"}
        )
    ]
