name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: docker compose build to warm things up
      run: |
        docker compose build
    - name: Ensure no fixes apply
      run: |
        docker compose run web pipenv run make bootstrap-dev fix
        git diff --exit-code # Error if fix changed things, to ensure stability
    - name: Check
      run: |
        docker compose run web pipenv run make bootstrap-dev check
    - name: collectstatic
      run: |
        docker compose run web pipenv run make collectstatic
    - name: Test
      run: |
        docker compose up --detach
        docker compose run web pipenv run make bootstrap-dev test
        docker compose down
